package com.student;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2014-11-23T00:35:30.460+11:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://student.com/", name = "ChangeStudentDetails")
@XmlSeeAlso({ObjectFactory.class})
public interface ChangeStudentDetails {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeName", targetNamespace = "http://student.com/", className = "com.student.ChangeName")
    @WebMethod
    @ResponseWrapper(localName = "changeNameResponse", targetNamespace = "http://student.com/", className = "com.student.ChangeNameResponse")
    public com.student.Student changeName(
        @WebParam(name = "arg0", targetNamespace = "")
        com.student.Student arg0
    );
}
